### ISSUE TITLE
`scope_guard` needs a way to release the ownership

### ISSUE THREAD

**Issue by ufownl** [Lingxi-Li/Happy_Hacking_CXX#6]
Just add a member function like `std::thread::detach`. It can name `dismiss`.
See [here](https://github.com/ufownl/ranger_proxy/blob/master/src/scope_guard.hpp#L42).

**Comment by Lingxi-Li** [comment]
The [current interface](https://github.com/Lingxi-Li/Happy_Hacking_CXX/blob/master/manual.md#scope_guard) is concise and hides the implementation details. Specifically, it doesn't require user to come up with a name, and use the name to define a variable of a specific type. This is quite neat. If the feature you requested is to be implemented, this would be impossible. Besides, I don't think a `dismiss()` method is ever required in a typical use-case. So, it may not be a good deal to sacrifice conciseness of the current interface in order to provide built-in support for a feature that is not commonly needed. If users do need this functionality, they can do it manually as follows:

``` C++
{
  bool dismissed = false;
  HHXX_ON_SCOPE_EXIT(
    if (! dismissed) ...
  );
  ...
  dismissed = true;
}
```

**Comment by Lingxi-Li** [comment]
As a workaround, just made `aggregate_wrapper<T[n]>::size` a member variable. Does it compile now?

**Comment by Lingxi-Li** [comment]
Relates to [this](http://programmers.stackexchange.com/q/308732/200711).
